Adding hardware Ledger support for Cosmostation
CudoVentures/cudos-station pull request #115
Opened 2022-10-15 10:14 UTC by SpaghettiOverload

Focing Amino signer when the connected Cosmostation account is a hardware Ledger.

2022-10-16 17:48 UTC, stefanpetkov90 approved these changes

2022-10-17 13:47 UTC, maptuhec requested changes

2022-10-17 13:47 UTC, maptuhec commented on src/ledgers/utils.ts
> +        client = await cosmostationSigner(import.meta.env.VITE_APP_CHAIN_ID)
skip the else, and diretcly return in in statement and after the if

2022-10-17 14:02 UTC, stefanpetkov90 commented on src/ledgers/utils.ts
> +        client = await cosmostationSigner(import.meta.env.VITE_APP_CHAIN_ID)
Done

2022-10-25 12:39 UTC, maptuhec approved these changes

2022-10-26 15:28 UTC, merged